# -*- coding: utf-8 -*-
"""KmeansIA2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WGh5cPCRPHnsf2dZMSllftKpzfo3D0Af
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

df = pd.read_csv("/content/sample_data/Mall_Customers.csv")
df.head()

df.info()

df.dtypes

df.describe()

df.isna().sum()
#treat null values

df.duplicated().sum()
#treat duplicates

#BAR PLOT
for column in df.select_dtypes(include=['object']).columns:
    plt.figure(figsize=(10, 5))
    df[column].value_counts().plot(kind='bar')
    plt.title(f'Bar Chart of {column}')
    plt.xlabel(column)
    plt.ylabel('Count')
    plt.show()

#SCATTER PLOT

numerical_columns = df.select_dtypes(include=['float64', 'int64']).columns
for i in range(len(numerical_columns)):
    for j in range(i + 1, len(numerical_columns)):
        plt.figure(figsize=(10, 6))
        sns.scatterplot(data=df, x=numerical_columns[i], y=numerical_columns[j])
        plt.title(f'Scatter Plot between {numerical_columns[i]} and {numerical_columns[j]}')
        plt.show()

sns.pairplot(df,corner=True)

numerical_columns = df.select_dtypes(include=['float64', 'int64']).columns
correlation_matrix = df[numerical_columns].corr()
print("Correlation matrix:\n", correlation_matrix)

plt.figure(figsize=(20, 10))
sns.heatmap(correlation_matrix, annot=True, fmt=".2f", cmap='inferno')
plt.title('Heatmap of Correlation Matrix')
plt.show()

scaler = MinMaxScaler()
scaler.fit(df[['Age']])
df['Age'] = scaler.transform(df[['Age']])
scaler.fit(df[['Spending Score (1-100)']])
df['Spending Score (1-100)'] = scaler.transform(df[['Spending Score (1-100)']])
print(df.head())
plt.scatter(df['Spending Score (1-100)'],df['Age'])

df.info()

km = KMeans(n_clusters=3)
y_predicted = km.fit_predict(df[['Spending Score (1-100)','Age']])
#y_predicted
df['cluster']=y_predicted
#df.head(25)
print(km.cluster_centers_)

df1 = df[df.cluster==0]
df2 = df[df.cluster==1]
df3 = df[df.cluster==2]
plt.scatter(df1['Spending Score (1-100)'],df1['Age'],color='green')
plt.scatter(df2['Spending Score (1-100)'],df2['Age'],color='red')
plt.scatter(df3['Spending Score (1-100)'],df3['Age'],color='black')
plt.scatter(km.cluster_centers_[:,0],km.cluster_centers_[:,1],color='purple',marker='*',label='centroid')
plt.xlabel('Spending Score (1-100)')
plt.ylabel('Age')
plt.legend()

sse = [] # The sum of Squared Errors =SSE
k_rng = range(1,10)
for k in k_rng:
   km = KMeans(n_clusters=k)
   km.fit(df[['Spending Score (1-100)','Age']])
   sse.append(km.inertia_)

plt.xlabel('K')
plt.ylabel('Sum of squared error')
plt.plot(k_rng,sse)

km = KMeans(n_clusters=3)
y_predicted = km.fit_predict(df[['Spending Score (1-100)','Age']])
print(y_predicted)

df['cluster']=y_predicted
print(df.head())

df1 = df[df.cluster==0]
df2 = df[df.cluster==1]
plt.scatter(df1['Spending Score (1-100)'],df1['Age'],color='green')
plt.scatter(df2['Spending Score (1-100)'],df2['Age'],color='red')
plt.scatter(km.cluster_centers_[:,0],km.cluster_centers_[:,1],color='purple',marker='*',label='centroid')
plt.xlabel('Spending Score (1-100)')
plt.ylabel('Age')
plt.legend()

#silhouette score is found
silhouette_score(df[['Spending Score (1-100)','Age']], km.fit_predict(df[['Spending Score (1-100)','Age']]))

