# -*- coding: utf-8 -*-
"""LVADSUSR141_AKILANBIMBY.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16v4VCHrJrCV0HIRx-oavt3fNtbv7zZSV
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#1
df=pd.read_csv("/content/sample_data/Final Dataset - IPL.csv")
print(df.info())
print("\nFirst 5 value:")
print(df.head())
print("\nLast 5 value:")
print(df.tail())
print()
print(df.describe())
print("\nNo of Rows and Column:")
print(df.shape)
print("\nDatatypes:")
print(df.dtypes)
print()
print(df.isnull().sum())

#2
print("No of null in each column:")
print(df.isnull().sum())
print("\nNo of duplicate value:")
df.duplicated().sum()

#From this we come to know that there is no Missing values or duplicate values in our dataset
#So our data is cleaned without any duplicate or missing values

#3
df.columns
df.dtypes

print("Descriptive_statistics:")
print("The mean is:",df['match_id'].mean())
print("The median is:",df['match_id'].median())
print("The mode is:",df['match_id'].mode())
print("The Standard Deviation is:",df['match_id'].std())
print("The variance is:",df['match_id'].var())
range=df['match_id'].max() - df['match_id'].min()
print("The range is:",range)

print("\n")
print("Descriptive_statistics on  first_ings_score:")
print("The mean is:",df['first_ings_score'].mean())
print("The median is:",df['first_ings_score'].median())
print("The mode is:",df['first_ings_score'].mode())
print("The Standard Deviation is:",df['first_ings_score'].std())
print("The variance is:",df['first_ings_score'].var())
range=df['first_ings_score'].max() - df['first_ings_score'].min()
print("The range is:",range)

print("\n")
print("Descriptive_statistics on  second_ings_score:")
print("The mean is:",df['second_ings_score'].mean())
print("The median is:",df['second_ings_score'].median())
print("The mode is:",df['second_ings_score'].mode())
print("The Standard Deviation is:",df['second_ings_score'].std())
print("The variance is:",df['second_ings_score'].var())
range=df['second_ings_score'].max() - df['second_ings_score'].min()
print("The range is:",range)

print("\n")
print("Descriptive_statistics on  highscore:")
print("The mean is:",df['highscore'].mean())
print("The median is:",df['highscore'].median())
print("The mode is:",df['highscore'].mode())
print("The Standard Deviation is:",df['highscore'].std())
print("The variance is:",df['highscore'].var())
range=df['highscore'].max() - df['highscore'].min()
print("The range is:",range)

df.info()
df.head()

#4
import matplotlib.pyplot as plt

#using various plots to visualize the dataset
# Histogram
df.hist(figsize=(10, 9))
plt.show()
print("\n\n\n")

# Scatter plot
plt.figure(figsize= (10,9))
plt.scatter(df['first_ings_score'], df['first_ings_wkts'])
plt.xlabel('first_ings_score')
plt.ylabel('first_ings_wkts')
plt.title('first_ings_score vs second_ings_score  ')
plt.show()
print("\n\n\n")

# Box plot
plt.figure(figsize= (10,9))
df.boxplot(column=['first_ings_score', 'second_ings_score'])
plt.show()
print("\n\n\n")

# 4.bar plot
plt.figure(figsize=(12, 8))
top_venue = df['venue'].value_counts().head(10)  # You can adjust the number here
sns.barplot(x=top_venue, y=top_venue.index)
plt.title('Top 10 venues')
plt.xlabel('Number of matches')
plt.ylabel('Venue')
plt.show()


# Pie chart
plt.figure(figsize= (10,9))
df1 = df['venue'].value_counts()
df1.head(10).plot(kind='pie')
plt.title('Venue where the IPL Happened')
plt.legend()
plt.ylabel('')
plt.show()

df.info()

#5
#correlation
num_col=df.select_dtypes(include =['float64','int64']).columns
d=df[num_col].corr()
sns.heatmap(d,annot=True)

#correlation can be done only for the numeric values
#so we taken the int and float value from the dataframe so that we can perform acordingly
#for correlatio we have heatmap from the seaborn
#it shows how thw values are correlated
#from the graph we can able to see
#->The first innings and the second innings scores are highly correlated
#-> the innings score and its wickets are strong negative correlated

#6 Outliers
plt.figure(figsize= (10,9))
df.boxplot(column=['first_ings_score', 'second_ings_score'])
plt.show()

plt.figure(figsize= (10,9))
df.boxplot(column=['first_ings_wkts', 'second_ings_wkts'])
plt.show()

plt.figure(figsize= (10,9))
df.boxplot(column=['first_ings_score', 'first_ings_wkts'])
plt.show()

plt.figure(figsize= (10,9))
df.boxplot(column=['second_ings_score', 'second_ings_wkts'])
plt.show()

# here i have done the boxplot to identify the outliers in the data
# Here i have choosen the data of the first and the second innings
# compared the first innings score with second innings score
# compared the innings wickets of both innings
# compared the first inning score and wicket
# the with the second innings score and wicket

df.info()

# 4.bar plot
plt.figure(figsize=(12, 8))
top_venue = df['venue'].value_counts().head(10)  # You can adjust the number here
sns.barplot(x=top_venue, y=top_venue.index)
plt.title('Top 10 venues')
plt.xlabel('Number of matches')
plt.ylabel('Venue')
plt.show()

7.
plt.figure(figsize=(12, 8))
top_venue = df['venue'].value_counts().head(10)  # You can adjust the number here
sns.barplot(x=top_venue, y=top_venue.index)
plt.title('Top 10 venues')
plt.xlabel('Number of matches')
plt.ylabel('Venue')
plt.show()

8.
# Scatter plot
plt.figure(figsize= (10,9))
plt.scatter(df['first_ings_score'], df['first_ings_wkts'])
plt.xlabel('first_ings_score')
plt.ylabel('first_ings_wkts')
plt.title('first_ings_score vs second_ings_score  ')
plt.show()
print("\n\n\n")

#9
"""
at first import the pandas,numpy,matplotlib.pyplot,seaborn
1.At first we imported the ipl data from the excel and convert it into data frame using the pandas read_csv
and find the first 5,last 5,data types,information,row value column value ect.

2.From the second question we found there is null or not using isnull then by this we came to know that there is no Missing values or duplicate values in our dataset
So our data is cleaned without any duplicate or missing values so we performed the following things

3.we found the mean,median,mode,variance,standard deviation,range for the numeric values and printed

4.we used graphs in the fourth questions likelike histogram,scatterplot,boxplot,barplot,pie chart
from histogram we found the max used venue
from scatterplot we found the first innings score and the wkts
from boxplot we foundtop 10 venue for matchs
from pie chart we found the venues and theri values

5.we can see correlation with the heatmap
with the help of heatmap #correlation can be done only for the numeric values
so we taken the int and float value from the dataframe so that we can perform acordingly
for correlatio we have heatmap from the seaborn
it shows how thw values are correlated
from the graph we can able to see
->The first innings and the second innings scores are highly correlated
-> the innings score and its wickets are strong negative correlated

6.we used box plot to find the outliers of the matchs and wickets which says that
 choosen  data of the first and the second innings
compared the first innings score with second innings score gives some outliers
compared the innings wickets of both innings no outliers
compared the first inning score and wicket some ouliers
the with the second innings score and wicket no outliers