# -*- coding: utf-8 -*-
"""Python_ assessment_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BuGha92KCJIh8kPPPXblb9S2-ZFIV4q7
"""

#1
length=float(input("Enter the length in meter:"))
width=float(input("Enter the width in meter:"))
area=length*width
print(area)
if area<=1000:
  print("small")
elif area>1000 and area<=2500:
  print("medium")
else:
  print("large")

#2
weight=float(input("Enter the weight in kg:"))
height=int(input("Enter height in m:"))
BMI=weight/(height*height)
print("Your BMI Value is ",BMI)

#3
dict1={
    {"name":"john","math":90,"science":97,"social":89},
    {"name":"alice","math":80,"science":92,"social":99},
    {"name":"bob","math":80,"science":77,"social":77}}
for key,values in dict1:
  print(dict[values])

#4
age=int(input("Enter your age:"))
if age<=12:
  print("You are a Children")
elif age>=13 and age<=19:
  print("You are a Teen")
elif age>=20 and age<=40:
  print("You are a adult")
else:
  print("You are a senior")

#5
Subscriber_ID=[1,2,3,4,5,6,7,8,9,10]
even_num=[]
for i in Subscriber_ID:
  if i%2==0:
    even_num.append(i)
print(even_num)

#6
stored_password="LVA@141"
password=input("Enter the Password:")
while(True):
  if stored_password==password:
    print("correct Password!")
    break
  else:
    print("Enter the correct password!!!")

#7
scores=[10,8,9,7,10]
def avg_score(a):
  sum=0
  for i in a:
    sum+=i
  avg=sum/len(a)
  print(avg)

avg_score(scores)

#8
vowels={'a','e','i','o','u','A','E','I','O','U'}
def count_vowels(a):
  count=0
  for i in a:
    if i in vowels:
      count+=1
  print(count)

comments="this content is good to gain knowledge"
count_vowels(comments)

#9
import datetime()
print(datetime.now())

#10
try:
  a=int(input("Enter the loan"))
  b=int(input("Enter the balance"))
  c=int(input("Enter tyhe interest"))
  remaining=loan-balance
  print(remaining)

except:
  print("Enter correctly!!")

#11
try:
  a=int(input("enter the value:"))
  b=int(input("enter another value:"))
  sum=a+b
  print(sum)
except:
  print("enter the correct value!")

#12
try:
  a=int(input("Enter a number:"))
  b=int(input("Enter another number:"))
  c=input("Choose any addition/subraction/multiplication/division:")
  if c=="addition":
    z=a+b
  elif c=="subraction":
    z=a-b
  elif c=="multiplication":
    z=a*b
  elif c=="division":
    z==a/b
  print(f"The {c} of {a} and {b} is",z)
except ZeroDivisionError:
  print("Enter a correct number to divide!!")

#13.
f=open("login.txt","w")
f.write("login\n")
f.write("check mail\n")
f.write("data check\n")
f.close()

f=open("login.txt","r")
print(f.read())

f=open("reporting.txt","w")
f.write("feedback:\n")
f.write("good\n")
f.write("average\n")
f.write("bad\n")
f.close()

file=open("reporting.txt","r")
print(file.read())

f=open("login.txt","a")
f.write("team meeting\n")
f.write("log out\n")

file=open("login.txt","r")
print(f.read())